// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRepo(arg1:string,arg2:boolean,arg3:string,arg4:string):Promise<void>;

export function ClearProxy():Promise<void>;

export function CopyPath(arg1:string):Promise<void>;

export function DoctorProject(arg1:string):Promise<main.DoctorResult>;

export function GetAppConfig():Promise<main.AppConfigDTO>;

export function GetCurrentProject():Promise<main.ProjectInfo>;

export function GetProxyInfo():Promise<Record<string, any>>;

export function GetVersionInfo():Promise<Record<string, any>>;

export function GlobalGC(arg1:boolean):Promise<Record<string, any>>;

export function GlobalList():Promise<Array<Record<string, any>>>;

export function GlobalStats():Promise<Record<string, any>>;

export function InitProject(arg1:Array<string>):Promise<void>;

export function ListAgents():Promise<Array<main.AgentInfo>>;

export function ListProjects():Promise<Array<main.ProjectItem>>;

export function ListRepos():Promise<Array<main.RepoItem>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PickProjectFolder():Promise<string>;

export function RemoveProject(arg1:string,arg2:boolean):Promise<void>;

export function RemoveRepo(arg1:string,arg2:boolean):Promise<void>;

export function RunDoctor():Promise<main.DoctorResult>;

export function RunSCC(arg1:string):Promise<main.SCCResult>;

export function SaveAppConfig(arg1:Record<string, any>):Promise<void>;

export function SetProxy(arg1:string):Promise<void>;

export function SwitchProject(arg1:string):Promise<main.ProjectInfo>;

export function UpdateRepo(arg1:string):Promise<void>;

export function WikiStatus():Promise<Record<string, any>>;

export function WikiSync():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
