// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ReferenceApp']['AddRepo'](arg1, arg2, arg3, arg4);
}

export function BrowseCacheByPathList(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['BrowseCacheByPathList'](arg1, arg2);
}

export function BrowseCacheByPathRead(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['BrowseCacheByPathRead'](arg1, arg2);
}

export function BrowseCacheByPathSearch(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['BrowseCacheByPathSearch'](arg1, arg2);
}

export function BrowseRepoList(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['BrowseRepoList'](arg1, arg2);
}

export function BrowseRepoRead(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['BrowseRepoRead'](arg1, arg2);
}

export function BrowseRepoSearch(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['BrowseRepoSearch'](arg1, arg2);
}

export function CheckWikiStatus(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['CheckWikiStatus'](arg1, arg2);
}

export function ClearProxy() {
  return window['go']['main']['ReferenceApp']['ClearProxy']();
}

export function CopyPath(arg1) {
  return window['go']['main']['ReferenceApp']['CopyPath'](arg1);
}

export function DeleteWikiEntry(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['DeleteWikiEntry'](arg1, arg2);
}

export function DiagnoseProject(arg1) {
  return window['go']['main']['ReferenceApp']['DiagnoseProject'](arg1);
}

export function DoctorProject(arg1) {
  return window['go']['main']['ReferenceApp']['DoctorProject'](arg1);
}

export function FixRepoLink(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['FixRepoLink'](arg1, arg2);
}

export function GetAppConfig() {
  return window['go']['main']['ReferenceApp']['GetAppConfig']();
}

export function GetCacheSize(arg1) {
  return window['go']['main']['ReferenceApp']['GetCacheSize'](arg1);
}

export function GetCurrentProject() {
  return window['go']['main']['ReferenceApp']['GetCurrentProject']();
}

export function GetProxyInfo() {
  return window['go']['main']['ReferenceApp']['GetProxyInfo']();
}

export function GetVersionInfo() {
  return window['go']['main']['ReferenceApp']['GetVersionInfo']();
}

export function GlobalGC(arg1) {
  return window['go']['main']['ReferenceApp']['GlobalGC'](arg1);
}

export function GlobalList() {
  return window['go']['main']['ReferenceApp']['GlobalList']();
}

export function GlobalStats() {
  return window['go']['main']['ReferenceApp']['GlobalStats']();
}

export function InitProject(arg1) {
  return window['go']['main']['ReferenceApp']['InitProject'](arg1);
}

export function ListAgents() {
  return window['go']['main']['ReferenceApp']['ListAgents']();
}

export function ListCachedRepos() {
  return window['go']['main']['ReferenceApp']['ListCachedRepos']();
}

export function ListProjects() {
  return window['go']['main']['ReferenceApp']['ListProjects']();
}

export function ListRepos() {
  return window['go']['main']['ReferenceApp']['ListRepos']();
}

export function ListWikiEntries(arg1) {
  return window['go']['main']['ReferenceApp']['ListWikiEntries'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['ReferenceApp']['OpenInExplorer'](arg1);
}

export function PickProjectFolder() {
  return window['go']['main']['ReferenceApp']['PickProjectFolder']();
}

export function PurgeCachedRepo(arg1) {
  return window['go']['main']['ReferenceApp']['PurgeCachedRepo'](arg1);
}

export function ReadWikiEntry(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['ReadWikiEntry'](arg1, arg2);
}

export function RecloneRepo(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['RecloneRepo'](arg1, arg2);
}

export function RelocateLocalRepo(arg1, arg2, arg3) {
  return window['go']['main']['ReferenceApp']['RelocateLocalRepo'](arg1, arg2, arg3);
}

export function RemoveProject(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['RemoveProject'](arg1, arg2);
}

export function RemoveRepo(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['RemoveRepo'](arg1, arg2);
}

export function RemoveRepoFromProject(arg1, arg2) {
  return window['go']['main']['ReferenceApp']['RemoveRepoFromProject'](arg1, arg2);
}

export function RunDoctor() {
  return window['go']['main']['ReferenceApp']['RunDoctor']();
}

export function RunSCC(arg1) {
  return window['go']['main']['ReferenceApp']['RunSCC'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['ReferenceApp']['SaveAppConfig'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['main']['ReferenceApp']['SetProxy'](arg1);
}

export function SwitchProject(arg1) {
  return window['go']['main']['ReferenceApp']['SwitchProject'](arg1);
}

export function UpdateRepo(arg1) {
  return window['go']['main']['ReferenceApp']['UpdateRepo'](arg1);
}

export function WikiStatus() {
  return window['go']['main']['ReferenceApp']['WikiStatus']();
}

export function WikiSync() {
  return window['go']['main']['ReferenceApp']['WikiSync']();
}

export function WindowClose() {
  return window['go']['main']['ReferenceApp']['WindowClose']();
}

export function WindowMaximize() {
  return window['go']['main']['ReferenceApp']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['ReferenceApp']['WindowMinimize']();
}
