// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRepo(arg1:string,arg2:boolean,arg3:string,arg4:string):Promise<void>;

export function BrowseCacheByPathList(arg1:string,arg2:string):Promise<Array<main.BrowserFileNode>>;

export function BrowseCacheByPathRead(arg1:string,arg2:string):Promise<main.BrowserFileResult>;

export function BrowseCacheByPathSearch(arg1:string,arg2:string):Promise<Array<main.BrowserFileNode>>;

export function BrowseRepoList(arg1:string,arg2:string):Promise<Array<main.BrowserFileNode>>;

export function BrowseRepoRead(arg1:string,arg2:string):Promise<main.BrowserFileResult>;

export function BrowseRepoSearch(arg1:string,arg2:string):Promise<Array<main.BrowserFileNode>>;

export function CheckWikiStatus(arg1:string,arg2:string):Promise<string>;

export function ClearProxy():Promise<void>;

export function CopyPath(arg1:string):Promise<void>;

export function DeleteWikiEntry(arg1:string,arg2:string):Promise<void>;

export function DiagnoseProject(arg1:string):Promise<Array<main.RepoDiagnosis>>;

export function DoctorProject(arg1:string):Promise<main.DoctorResult>;

export function FixRepoLink(arg1:string,arg2:string):Promise<void>;

export function GetAppConfig():Promise<main.AppConfigDTO>;

export function GetCacheSize(arg1:string):Promise<number>;

export function GetCacheTopN(arg1:number):Promise<Array<main.CacheTopItem>>;

export function GetCurrentProject():Promise<main.ProjectInfo>;

export function GetDirSizeAsync(arg1:string):Promise<number>;

export function GetProxyInfo():Promise<Record<string, any>>;

export function GetVersionInfo():Promise<Record<string, any>>;

export function GlobalGC(arg1:boolean):Promise<Record<string, any>>;

export function GlobalList():Promise<Array<Record<string, any>>>;

export function GlobalStats():Promise<Record<string, any>>;

export function InitProject(arg1:Array<string>):Promise<void>;

export function ListAgents():Promise<Array<main.AgentInfo>>;

export function ListCachedRepos():Promise<Array<main.CachedRepoItem>>;

export function ListProjects():Promise<Array<main.ProjectItem>>;

export function ListRepos():Promise<Array<main.RepoItem>>;

export function ListWikiEntries(arg1:string):Promise<Array<main.WikiEntry>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function PickProjectFolder():Promise<string>;

export function PurgeCachedRepo(arg1:string):Promise<void>;

export function ReadWikiEntry(arg1:string,arg2:string):Promise<string>;

export function RecloneRepo(arg1:string,arg2:string):Promise<void>;

export function RelocateLocalRepo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveProject(arg1:string,arg2:boolean):Promise<void>;

export function RemoveRepo(arg1:string,arg2:boolean):Promise<void>;

export function RemoveRepoFromProject(arg1:string,arg2:string):Promise<void>;

export function RunDoctor():Promise<main.DoctorResult>;

export function RunSCC(arg1:string):Promise<main.SCCResult>;

export function SaveAppConfig(arg1:Record<string, any>):Promise<void>;

export function SetProxy(arg1:string):Promise<void>;

export function SwitchProject(arg1:string):Promise<main.ProjectInfo>;

export function UpdateRepo(arg1:string):Promise<void>;

export function WikiStatus():Promise<Record<string, any>>;

export function WikiSync():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
